modeloAutenticacao/config/routes.rb
Rails.application.routes.draw do
  resources :carros

  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "registrations" }
  
  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
  end

  root  'carros#index'

end

modeloAutenticacao/app/models/carro.rb
class Carro < ActiveRecord::Base
end

modeloAutenticacao/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

modeloAutenticacao/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

modeloAutenticacao/app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action  :set_carro, only: [:show, :edit, :update, :destroy ] 
  before_action :authenticate_user!
  
  respond_to :html

  def index
      @user = current_user
      @carros = Carro.where( [ "user_id = ? " , @user.id ] )
      respond_with(@carros)
  end

  def show
    respond_with(@carro)
  end

  def new
    @carro = Carro.new
    respond_with(@carro)
  end

  def edit
  end

  def create
    @carro = Carro.new(carro_params)
    @carro.save

    @user = User.new(:email => 'test@example.com', :password => 'password', :password_confirmation => 'password')
    @user.save

    respond_with(@carro)
  end

  def update
    @carro.update(carro_params)
    respond_with(@carro)
  end

  def destroy
    @carro.destroy
    respond_with(@carro)
  end

  private
    def set_carro
      @carro = Carro.find(params[:id])
    end

    def carro_params
      params.require(:carro).permit(:nome, :marca, :ano , :user_id)
    end
end

modeloAutenticacao/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  # GET /resource/sign_up
  def new
    build_resource({})
    respond_with self.resource
  end
  

  def show
  end


  # POST /resource
  def create
    build_resource(sign_up_params)
    if resource.save
      yield resource if block_given?
        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_flashing_format?
          respond_with resource, :location => after_sign_up_path_for(resource)
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
          expire_data_after_sign_in!
          respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
 
  def after_sign_up_path_for(resource)
      case resource
        when User 
          then root_path
        else 
          root_path
      end
  end
 
end

modeloAutenticacao/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

modeloAutenticacao/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

modeloAutenticacao/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

modeloAutenticacao/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

modeloAutenticacao/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #     super do |resource|
  #      BackgroundWorker.trigger(resource)
  #    end
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

modeloAutenticacao/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

modeloAutenticacao/app/helpers/application_helper.rb
module ApplicationHelper
end

modeloAutenticacao/app/helpers/carros_helper.rb
module CarrosHelper
end

modeloAutenticacao/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

modeloAutenticacao/app/views/carros/_form.html.erb
<%= form_for(@carro) do |f| %>
  <% if @carro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
      <% @carro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :ano %><br>
    <%= f.number_field :ano %>
  </div>


  <%= f.hidden_field :user_id , :value => current_user.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

modeloAutenticacao/app/views/carros/edit.html.erb
<h1>Editing carro</h1>

<%= render 'form' %>

<%= link_to 'Show', @carro %> |
<%= link_to 'Back', carros_path %>

modeloAutenticacao/app/views/carros/index.html.erb
<h1>Listing carros</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Marca</th>
      <th>Ano</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carros.each do |carro| %>
      <tr>
        <td><%= carro.nome %></td>
        <td><%= carro.marca %></td>
        <td><%= carro.ano %></td>
        <td><%= link_to 'Show', carro %></td>
        <td><%= link_to 'Edit', edit_carro_path(carro) %></td>
        <td><%= link_to 'Destroy', carro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carro', new_carro_path %>

modeloAutenticacao/app/views/carros/new.html.erb
<h1>New carro</h1>

<%= render 'form' %>

<%= link_to 'Back', carros_path %>

modeloAutenticacao/app/views/carros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @carro.nome %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @carro.marca %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @carro.ano %>
</p>

<%= link_to 'Edit', edit_carro_path(@carro) %> |
<%= link_to 'Back', carros_path %>

modeloAutenticacao/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ModeloAutenticacao</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<p id="notice"><%= notice %></p>

 <% if current_user.present? %>
      <%= current_user.email %>
      <%= link_to('Sair', destroy_user_session_path, :method => :delete) %>
    <% else %>
      <%= link_to "Cadastrar", new_user_registration_path %>/
      <%= link_to "Entrar", new_user_session_path %>
  <% end %>

<%= yield %>

</body>
</html>

modeloAutenticacao/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>